### ISSUE TITLE
ImportError: No module named _util

### ISSUE THREAD

**Issue by iinux** [moxie0/sslstrip#24]
```
[abui@shakespeare sslstrip]$ sslstrip -l 8080                      
Traceback (most recent call last):
  File "/usr/bin/sslstrip", line 30, in <module>
    from sslstrip.StrippingProxy import StrippingProxy
  File "/usr/lib/python2.7/site-packages/sslstrip/StrippingProxy.py", line 20, in <module>
    from ClientRequest import ClientRequest
  File "/usr/lib/python2.7/site-packages/sslstrip/ClientRequest.py", line 25, in <module>
    from twisted.internet import ssl
  File "/usr/lib64/python2.7/site-packages/twisted/internet/ssl.py", line 230, in <module>
    from twisted.internet._sslverify import (
  File "/usr/lib64/python2.7/site-packages/twisted/internet/_sslverify.py", line 15, in <module>
    from OpenSSL._util import lib as pyOpenSSLlib
ImportError: No module named _util
```

**Comment by jacklam718** [comment]
@iinux this [stackoverflow](https://stackoverflow.com/questions/50324329/running-scrapy-but-it-error-no-module-named-util) works for me

**Comment by kanwal08** [comment]
> @iinux this [stackoverflow](https://stackoverflow.com/questions/50324329/running-scrapy-but-it-error-no-module-named-util) works for me

Hello
This isn't working for me, it says already up to date but i am still getting the same error

**Comment by TekuSP** [comment]
pip install pyopenssl --user --upgrade

Old pyopenssl
