### ISSUE TITLE
pycparser error all required packages is install but this error occured

### ISSUE THREAD

**Issue by Thunderbeast000** [moxie0/sslstrip#38]
Traceback (most recent call last):
  File "/usr/local/bin/sslstrip", line 30, in <module>
    from sslstrip.StrippingProxy import StrippingProxy
  File "/usr/local/lib/python2.7/dist-packages/sslstrip/StrippingProxy.py", line 20, in <module>
    from ClientRequest import ClientRequest
  File "/usr/local/lib/python2.7/dist-packages/sslstrip/ClientRequest.py", line 25, in <module>
    from twisted.internet import ssl
  File "/usr/lib/python2.7/dist-packages/twisted/internet/ssl.py", line 59, in <module>
    from OpenSSL import SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 60, in <module>
    class Binding(object):
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 109, in Binding
    libraries=_get_libraries(sys.platform)
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/utils.py", line 97, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/utils.py", line 105, in build_ffi
    ffi = FFI()
  File "/usr/lib/python2.7/dist-packages/cffi/api.py", line 65, in __init__
    from . import cparser
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 7, in <module>
    import pycparser
ImportError: No module named pycparser

**Comment by micwoj92** [comment]
Do you have python2-pycparser installed?
